### ISSUE TITLE
Requests for older linux-headers.deb

### ISSUE THREAD

**Issue by oreme2** [volumio/platform-x86#28]
sorry I cannot install the newest kernel version of 6.1.22 with linux-image.deb，so the linux-headers.deb is useless for me also.
i need the linux-headers.deb of 5.10.165 version for the RTL wi-fi driver installation. thank you
![image](https://user-images.githubusercontent.com/38098761/229603761-85b2ca34-7d50-45a9-81a0-0a8225073bc9.png)
![image](https://user-images.githubusercontent.com/38098761/229603994-d6e97391-dfae-461d-9067-29625aa0eec4.png)
![image](https://user-images.githubusercontent.com/38098761/229604121-f424226a-529b-4c2a-8131-fc6864099a92.png)
![image](https://user-images.githubusercontent.com/38098761/229604376-3098c6d1-a54c-42ce-99c4-7fbaf0350d66.png)

**Comment by gkkpch** [comment]
You are not supposed to install .deb files at all, they are part of the platform-x86 repo.
Platform-86 is only intended to be used for the x86 Volumio image build process. That process is Volumio-specific. And 6.1.22 has not even been released yet, that is all WIP.

Anyway, why do you insist on installing the rtl8822bu driver? It is supported with our kernel 5.10.165 out-of-the-box! AFAIR I included rtl88x2bu with version 5.10.95, along with rtl8723du, rtl8811cu and rtl8812au.
